<?php

define('TOOBASIC_TESTS_ASSETS_DIR', __DIR__);
define('TOOBASIC_TESTS_DIR', dirname(TOOBASIC_TESTS_ASSETS_DIR));

define('TOOBASIC_TESTS_ACASES_DIR', TOOBASIC_TESTS_ASSETS_DIR.'/cases');
define('TOOBASIC_TESTS_AINCLUDES_DIR', TOOBASIC_TESTS_ASSETS_DIR.'/includes');
