#!/bin/bash
#
case $TRAVIS_PHP_VERSION in
	'5.5')
		export TRAVISCI_PHPUNIT_CONF='';
		export TRAVISCI_PHPUNIT_VERSION='4.8.24';
		export TRAVISCI_PHPUNIT_SELENIUM_VERSION='2.0.2';
		;;
	'5.6')
		export TRAVISCI_PHPUNIT_CONF='';
		export TRAVISCI_PHPUNIT_VERSION='5.7';
		export TRAVISCI_PHPUNIT_SELENIUM_VERSION='3.0.3';
		;;
	'7.0')
		export TRAVISCI_PHPUNIT_CONF='-7.0';
		export TRAVISCI_PHPUNIT_VERSION='5.7';
		export TRAVISCI_PHPUNIT_SELENIUM_VERSION='3.0.3';
		;;
	'7.1')
		export TRAVISCI_PHPUNIT_CONF='-7.0';
		export TRAVISCI_PHPUNIT_VERSION='5.7';
		export TRAVISCI_PHPUNIT_SELENIUM_VERSION='3.0.3';
		;;
	'nightly')
		export TRAVISCI_PHPUNIT_CONF='-7.0';
		export TRAVISCI_PHPUNIT_VERSION='5.7';
		export TRAVISCI_PHPUNIT_SELENIUM_VERSION='3.0.3';
		;;
esac;

echo "PHP Version:                       '${TRAVIS_PHP_VERSION}'";
echo "TRAVISCI_PHPUNIT_CONF:             '${TRAVISCI_PHPUNIT_CONF}'";
echo "TRAVISCI_PHPUNIT_VERSION:          '${TRAVISCI_PHPUNIT_VERSION}'";
echo "TRAVISCI_PHPUNIT_SELENIUM_VERSION: '${TRAVISCI_PHPUNIT_SELENIUM_VERSION}'";
