mysql -u root -e "CREATE USER '${TRAVISCI_MYSQL_USERNAME}'@'%' IDENTIFIED BY '${TRAVISCI_MYSQL_PASSWORD}'"
mysql -u root -e "CREATE USER '${TRAVISCI_MYSQL_USERNAME}'@'localhost' IDENTIFIED BY '${TRAVISCI_MYSQL_PASSWORD}'"
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '${TRAVISCI_MYSQL_USERNAME}'@'%'"
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '${TRAVISCI_MYSQL_USERNAME}'@'localhost'"
