---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.css"
  - "**.js"
exclude_paths:
- config/**/*
- cache/**/*
- site/**/*
- libraries/**/*
- "modules/starterdoc/scripts/strapdown.js"
- "modules/starterdoc/scripts/strapdown.css"
- "modules/starterdoc/styles/jquery.cssemoticons.css"